### PR TITLE
Fix issues with column resizing.

### PR DESCRIPTION
**Pull request by Xanir**
* Fixes performance issues when quickly dragging a columns over other columns.
 * Move all attributes from TABLE to wrapping DIV

### CODE REVIEW

**Comment by jadrake75** [comment]
Maybe I am missing something, but when I pulled this pull request to test it only allows move of columns.  I am also thinking the column "icon" for draggable columns should be a hand.  ie. resize when it is on the edges and hand in the middle.  We need to be careful about sort though....

**Comment by Xanir** [comment]
This fix addresses a performance issue I saw with dragging. When the dragged column was quickly moved over many columns the drop indicator would lag behind and take a while to catch up.

**Comment by jadrake75** [comment]
Ok, I just did a pull request and merged a change that absorbed some of the changes here (except the resize changes).  I think we need to rework this from master.

**Comment by Xanir** [comment]
Ignore my last comment, I was talking about column *reordering*.
If you still have the submission handly can you check that the TDs are relatively positioned and there is a div absolutely position to the right of the TD.

**Comment by Xanir** [comment]
Commiting new version opposed to trying to fast-forward this commit.

**Pull request closed without merging**
