### PR TITLE
Fix issues with column resizing.

### PR DESCRIPTION
**Pull request by Xanir**
- Ensure cursor icon is reset.
- Allow continued column resizing even when cursor is outside of the THEAD.
- Fix from last submission: Allow first column to be resizable.

### CODE REVIEW

**Comment by Xanir** [comment]
When testing this update your bower dependencies

**Comment by jadrake75** [comment]
I am getting an undefined in here:

this.registerMouseDragHandler = function(mdElem, startMoveFunction, moveFunction, endMoveFunction, delay) {

within Services.min.js

the mdElem was just a DOM element so "on" was not valid.  If I did a $(mdElem).on it worked.

So either the nz-services needs to be better protective or the caller of this needs to wrap/parse the element better. (I did a "grunt clean & bower install & grunt dev")

**Comment by jadrake75** [comment]
I have checked in an update on the branch with proposed fixes

**Comment by Xanir** [comment]
Hmm, in the latest version v0.1.8 of nzServices the `.on` function is not used.
See here:
https://github.com/EnzeyNet/Services/blob/master/src/nzEventHelper.js#L121

**Comment by jadrake75** [comment]
Issue was related to bower NOT updating the Services files from 0.1.7.  Done and change reverted.

**Pull request merged**
